# Generated by Django 4.2.29 on 2026-07-20 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Téléphone')),
                ('job_title', models.CharField(blank=True, max_length=120, verbose_name='Fonction')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Organisation')),
                ('department', models.CharField(blank=True, max_length=120, verbose_name='Département')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'English')], default='fr', max_length=8, verbose_name='Langue')),
                ('timezone', models.CharField(default='Africa/Abidjan', max_length=64, verbose_name='Fuseau horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
