# Generated by Django 4.2.29 on 2026-04-13 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionSimulationProject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('provider', models.CharField(choices=[('RUNWAY', 'Runway'), ('VEO', 'Google Veo')], default='RUNWAY', max_length=20)),
                ('style', models.CharField(choices=[('REALISTIC', 'Réaliste'), ('CINEMATIC', 'Cinématique'), ('PREMIUM', 'Premium'), ('DOCUMENTARY', 'Documentaire')], default='REALISTIC', max_length=20)),
                ('camera_style', models.CharField(choices=[('DRONE', 'Drone'), ('STREET', 'Vue rue'), ('MIXED', 'Mixte'), ('ORBIT', 'Orbit'), ('FIXED', 'Fixe')], default='MIXED', max_length=20)),
                ('target_duration_seconds', models.PositiveIntegerField(default=30)),
                ('aspect_ratio', models.CharField(default='16:9', max_length=20)),
                ('target_resolution', models.CharField(default='1280x720', max_length=20)),
                ('include_audio', models.BooleanField(default=False)),
                ('include_voiceover', models.BooleanField(default=False)),
                ('include_branding', models.BooleanField(default=True)),
                ('include_watermark', models.BooleanField(default=True)),
                ('language', models.CharField(default='fr', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Brouillon'), ('QUEUED', 'En file'), ('STORYBOARDING', 'Storyboard'), ('GENERATING_IMAGES', 'Génération images'), ('GENERATING_VIDEOS', 'Génération vidéos'), ('ASSEMBLING', 'Assemblage'), ('COMPLETED', 'Terminée'), ('FAILED', 'Échec'), ('CANCELED', 'Annulée')], db_index=True, default='DRAFT', max_length=30)),
                ('prompt_seed', models.TextField(blank=True)),
                ('negative_prompt', models.TextField(blank=True)),
                ('business_context', models.JSONField(blank=True, default=dict)),
                ('technical_context', models.JSONField(blank=True, default=dict)),
                ('final_video', models.FileField(blank=True, null=True, upload_to='ai_simulations/final/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='ai_simulations/thumbs/')),
                ('total_scenes', models.PositiveIntegerField(default=0)),
                ('completed_scenes', models.PositiveIntegerField(default=0)),
                ('progress_percent', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_simulations', to='parcelaire.propertyasset')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_simulations_created', to=settings.AUTH_USER_MODEL)),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_simulations', to='parcelaire.parcel')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='construction_simulations', to='parcelaire.realestateprogram')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionSimulationScene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('phase_code', models.CharField(blank=True, max_length=50)),
                ('duration_seconds', models.PositiveIntegerField(default=5)),
                ('shot_type', models.CharField(blank=True, max_length=100)),
                ('environment', models.CharField(blank=True, max_length=255)),
                ('weather', models.CharField(blank=True, default='clear daylight', max_length=100)),
                ('camera_motion', models.CharField(blank=True, default='slow cinematic movement', max_length=100)),
                ('prompt_text', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='ai_simulations/scenes/reference/')),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='ai_simulations/scenes/generated_images/')),
                ('generated_video', models.FileField(blank=True, null=True, upload_to='ai_simulations/scenes/generated_videos/')),
                ('provider_job_id', models.CharField(blank=True, max_length=255)),
                ('provider_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(db_index=True, default='PENDING', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='ai_construction.constructionsimulationproject')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('simulation', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ConstructionSimulationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='ai_construction.constructionsimulationscene')),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='ai_construction.constructionsimulationproject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionSimulationAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('PHOTO', 'Photo'), ('PLAN', 'Plan'), ('RENDER', 'Render'), ('DRONE', 'Drone'), ('STYLE', 'Style'), ('LOGO', 'Logo')], max_length=20)),
                ('file', models.FileField(upload_to='ai_simulations/assets/')),
                ('label', models.CharField(blank=True, max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='ai_construction.constructionsimulationproject')),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionSimulationVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('config_snapshot', models.JSONField(blank=True, default=dict)),
                ('prompt_snapshot', models.JSONField(blank=True, default=dict)),
                ('final_video', models.FileField(blank=True, null=True, upload_to='ai_simulations/versions/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='ai_construction.constructionsimulationproject')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('simulation', 'version_number')},
            },
        ),
    ]
