"""
Django settings for parcelaireKG project.

Generated by 'django-admin startproject' using Django 4.2.29.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent


def _split_env(name, default=""):
    """
    Split a comma-separated env var into a clean list.

    Bascule sur `default` si la variable est absente OU vide après
    nettoyage (utile quand un docker-compose passe `VAR=` sans valeur :
    `os.environ.get(name, default)` ne renverrait alors PAS le default
    mais la chaîne vide, et la liste serait `[]` → Django bloque tout
    avec un Bad Request.)
    """
    raw = (os.environ.get(name) or "").strip()
    if not raw:
        raw = (default or "").strip()
    return [item.strip() for item in raw.split(",") if item.strip()]


# SECURITY WARNING: keep the secret key used in production secret!
# La clé est lue depuis l'environnement. Une valeur de repli est fournie
# uniquement pour permettre les tâches sans env (ex. `manage.py check`),
# et porte le préfixe "django-insecure-" pour rester détectable.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-fallback-do-not-use-in-production",
)

# SECURITY WARNING: don't run with debug turned on in production!
# `DEBUG` est piloté par variable d'env. Faux par défaut pour éviter
# d'exposer la stack en cas d'oubli de configuration.
DEBUG = os.environ.get("DEBUG", "False").lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = _split_env(
    "ALLOWED_HOSTS",
    default="datarium-dev.com,localhost,127.0.0.1",
)

CSRF_TRUSTED_ORIGINS = _split_env(
    "CSRF_TRUSTED_ORIGINS",
    default="https://datarium-dev.com",
)

SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
# Application definition

INSTALLED_APPS = [
    # 'grappelli',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'django.contrib.humanize',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'rest_framework',
    'rest_framework.authtoken',
    'import_export',
    'mathfilters',
    'django_select2',
    'widget_tweaks',
    'djmoney',
    # 'autocomplete_light',
    # 'import_export_extensions',
    'tinymce',
    'simple_history',
    'num2words',
    'django_filters',
    'qr_code',
    'notifications',
    'weasyprint',
    "csp",
    'drf_spectacular',
    'corsheaders',
    'parcelaire',
    'ai_construction'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise sert /static/ depuis STATIC_ROOT (CSS Tailwind compilé,
    # JS, images, polices…) sans nécessiter Nginx en frontal.
    # Doit impérativement être placé juste après SecurityMiddleware.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
    "allauth.account.middleware.AccountMiddleware",
    # CSP : doit être chargé après SecurityMiddleware pour pouvoir injecter
    # les headers Content-Security-Policy.
    "csp.middleware.CSPMiddleware",
]

# WhiteNoise : compression (gzip + brotli) et cache busting (manifest).
# Le manifest est plus strict, on l'active seulement quand on n'est PAS en
# debug pour éviter de planter le dev si un asset n'a pas été collecté.
WHITENOISE_COMPRESSION_ENABLED = True
WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365  # 1 an
WHITENOISE_INDEX_FILE = False  # ne pas servir d'index dans /static/

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # En dev (DEBUG=True) → serveur runserver + StaticFilesStorage simple.
        # En prod → CompressedManifestStaticFilesStorage (cache long, hashé).
        "BACKEND": (
            "whitenoise.storage.CompressedStaticFilesStorage"
            if DEBUG
            else "whitenoise.storage.CompressedManifestStaticFilesStorage"
        ),
    },
}

# =====================================================================
# Content Security Policy (django-csp 4.x)
# =====================================================================
# La cartographie utilise Leaflet, Tailwind CDN, Alpine.js, Font Awesome,
# Google Fonts et les tuiles OpenStreetMap. La policy doit donc autoriser
# ces sources tout en bloquant les iframes et les frames.
#
# IMPORTANT — `'unsafe-eval'` est requis :
# Alpine.js v3 (build CDN unpkg) compile chacune de ses directives
# (`x-data`, `x-show`, `@click`, `:class`, etc.) via `new Function(...)`,
# ce qui est interdit sans `'unsafe-eval'`. La CSP reste utile contre
# l'injection de scripts cross-origin et de balises iframe ; elle ne
# protège juste plus contre l'évaluation dynamique côté Alpine.
# Pour s'en débarrasser à terme, basculer sur `@alpinejs/csp` (qui ne
# supporte que des expressions simples) ou compiler Alpine en build.
#
# `CSP_ENABLED=False` permet de désactiver complètement la CSP via env
# (utile en dev pour pister un nouveau plantage).
CSP_ENABLED = os.environ.get("CSP_ENABLED", "True").lower() in {"1", "true", "yes", "on"}

if CSP_ENABLED:
    CONTENT_SECURITY_POLICY = {
        "DIRECTIVES": {
            "default-src": ["'self'"],
            "script-src": [
                "'self'",
                "'unsafe-inline'",
                "'unsafe-eval'",  # requis par Alpine.js v3 (CDN)
                # cdn.tailwindcss.com retiré : Tailwind est compilé en
                # local (`npm run build:css`) → /static/css/tailwind.css
                "https://unpkg.com",
                "https://cdnjs.cloudflare.com",
            ],
            "style-src": [
                "'self'",
                "'unsafe-inline'",
                "https://fonts.googleapis.com",
                "https://unpkg.com",
                "https://cdnjs.cloudflare.com",
            ],
            "font-src": [
                "'self'",
                "https://fonts.gstatic.com",
                "https://cdnjs.cloudflare.com",
                "data:",
            ],
            "img-src": [
                "'self'",
                "data:",
                "blob:",
                "https://*.tile.openstreetmap.org",
                "https://*.basemaps.cartocdn.com",
                # Markers / sprites Leaflet servis depuis le CDN unpkg.
                "https://unpkg.com",
            ],
            "connect-src": [
                "'self'",
                # Source maps Leaflet / leaflet.markercluster (DevTools).
                # Sans ces entrées, la console affiche un warning CSP à
                # chaque ouverture des outils de développement.
                "https://unpkg.com",
                "https://cdnjs.cloudflare.com",
            ],
            "frame-ancestors": ["'none'"],
            "base-uri": ["'self'"],
            "object-src": ["'none'"],
        },
    }
else:
    # CSP désactivée — on retire le middleware pour éviter qu'il n'envoie
    # un header vide qui bloquerait quand même certaines ressources.
    MIDDLEWARE = [m for m in MIDDLEWARE if m != "csp.middleware.CSPMiddleware"]

ROOT_URLCONF = 'parcelaireKG.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'parcelaireKG.wsgi.application'
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr'

# Aligné sur le calendrier métier (Côte d'Ivoire) et sur Celery (cf. CELERY_TIMEZONE).
TIME_ZONE = os.environ.get("TIME_ZONE", "Africa/Abidjan")

USE_I18N = True

USE_TZ = True
SITE_ID = int(os.environ.get("SITE_ID", "1"))

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


MEDIA_URL = '/media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

# Statics : valeurs sensibles redéfinies dans dev.py / prod.py si besoin,
# mais on les définit ici pour que WhiteNoise et `collectstatic` les
# trouvent dans tous les environnements (même quand le module est
# importé sans la sous-config).
STATIC_URL = '/static/'
STATIC_ROOT = Path(os.environ.get('STATIC_ROOT', BASE_DIR / 'staticfiles'))
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CELERY_BEAT_SCHEDULE = {
    "sync-kaydan-stale-parcels-every-30-min": {
        "task": "parcelaire.tasks.sync_kaydan_stale_parcels_task",
        "schedule": 60.0 * 30,
    },
    "sync-kaydan-full-nightly": {
        "task": "parcelaire.tasks.sync_kaydan_all_parcels_task",
        "schedule": crontab(hour=2, minute=0),
    },
}

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"
CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Africa/Abidjan"

EXTERNAL_LOTS_API_URL = os.environ.get("EXTERNAL_LOTS_API_URL")
EXTERNAL_LOTS_API_KEY = os.environ.get("EXTERNAL_LOTS_API_KEY")
EXTERNAL_LOTS_API_USERNAME = os.environ.get("EXTERNAL_LOTS_API_USERNAME")
EXTERNAL_LOTS_API_PASSWORD = os.environ.get("EXTERNAL_LOTS_API_PASSWORD")



SAP_BASE_URL = os.getenv("SAP_BASE_URL", "").rstrip("/")
SAP_TOKEN_URL = os.getenv("SAP_TOKEN_URL", "")
SAP_CLIENT_ID = os.getenv("SAP_CLIENT_ID", "")
SAP_CLIENT_SECRET = os.getenv("SAP_CLIENT_SECRET", "")
SAP_TIMEOUT = int(os.getenv("SAP_TIMEOUT", "60"))
SAP_VERIFY_SSL = os.getenv("SAP_VERIFY_SSL", "true").lower() == "true"

