# Generated by Django 4.2.29 on 2026-07-29 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_copilot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copilotconversation',
            options={'ordering': ['-updated_at'], 'permissions': [('use_sql_agent', "Peut utiliser l'agent SQL du Copilote (lecture seule)")]},
        ),
    ]
