# Generated by Django 4.2.29 on 2026-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_copilot', '0002_alter_copilotconversation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copilottoolcall',
            name='status',
            field=models.CharField(choices=[('ok', 'OK'), ('denied', 'Refusé (permission)'), ('needs_confirmation', 'Confirmation requise'), ('confirmed', 'Confirmée (effet de bord exécuté)'), ('rejected_confirm', 'Confirmation refusée (outil non confirmable)'), ('unknown', 'Outil inconnu'), ('error', 'Erreur')], max_length=32),
        ),
    ]
