# Generated by Django 4.2.29 on 2026-04-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestateprogram',
            name='has_orthophoto',
        ),
        migrations.RemoveField(
            model_name='realestateprogram',
            name='orthophoto_bounds',
        ),
        migrations.RemoveField(
            model_name='realestateprogram',
            name='orthophoto_folder',
        ),
        migrations.RemoveField(
            model_name='realestateprogram',
            name='orthophoto_max_zoom',
        ),
        migrations.RemoveField(
            model_name='realestateprogram',
            name='orthophoto_min_zoom',
        ),
    ]
