# Generated by Django 4.2.29 on 2026-03-11 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planifié'), ('NOT_STARTED', 'Non démarré'), ('IN_PROGRESS', 'En cours'), ('ON_HOLD', 'Suspendu'), ('COMPLETED', 'Achevé'), ('CANCELLED', 'Annulé')], default='PLANNED', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('site_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_projects', to='parcelaire.propertyasset')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_projects', to='parcelaire.parcel')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('report_date', models.DateField()),
                ('stage', models.CharField(choices=[('SITE_INSTALLATION', 'Installation chantier'), ('FOUNDATION', 'Fondations'), ('BASEMENT', 'Soubassement'), ('WALLS', 'Élévation murs'), ('SLAB', 'Dalle'), ('ROOF', 'Toiture'), ('PLUMBING', 'Plomberie'), ('ELECTRICITY', 'Électricité'), ('PLASTERING', 'Enduits'), ('PAINTING', 'Peinture'), ('FINISHING', 'Finitions'), ('DELIVERY', 'Livraison'), ('OTHER', 'Autre')], default='OTHER', max_length=30)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True, null=True)),
                ('issues', models.TextField(blank=True, null=True)),
                ('next_actions', models.TextField(blank=True, null=True)),
                ('weather_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('recorded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='parcelaire.constructionproject')),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='construction_progress/%Y/%m/')),
                ('caption', models.TextField(blank=True, null=True)),
                ('shot_date', models.DateField(blank=True, null=True)),
                ('view_type', models.CharField(choices=[('FRONT', 'Façade'), ('BACK', 'Arrière'), ('LEFT', 'Côté gauche'), ('RIGHT', 'Côté droit'), ('INTERIOR', 'Intérieur'), ('AERIAL', 'Vue aérienne'), ('DETAIL', 'Détail'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('is_cover', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parcelaire.constructionproject')),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='parcelaire.constructionupdate')),
            ],
            options={
                'ordering': ['sort_order', '-shot_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Vidéo')], default='IMAGE', max_length=10)),
                ('file', models.FileField(upload_to='construction_media/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('shot_date', models.DateField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('construction_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='parcelaire.constructionproject')),
                ('update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='parcelaire.constructionupdate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
