# Generated by Django 4.2.29 on 2026-07-16 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcelaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('dedup_key', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Clé de déduplication')),
                ('rule', models.CharField(db_index=True, max_length=60, verbose_name='Règle')),
                ('level', models.CharField(choices=[('CRITIQUE', 'Critique'), ('ELEVE', 'Élevé'), ('MOYEN', 'Moyen'), ('FAIBLE', 'Faible'), ('INFO', 'Information')], db_index=True, default='MOYEN', max_length=20, verbose_name='Niveau')),
                ('status', models.CharField(choices=[('NEW', 'Nouvelle'), ('ACK', 'Accusée'), ('RESOLVED', 'Résolue')], db_index=True, default='NEW', max_length=20, verbose_name='Statut')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='Détail')),
                ('metric', models.CharField(blank=True, max_length=120, null=True, verbose_name='Indicateur')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='Valeur')),
                ('first_detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Première détection')),
                ('last_detected_at', models.DateTimeField(auto_now=True, verbose_name='Dernière détection')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='parcelaire.customer')),
                ('parcel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parcelaire.parcel')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parcelaire.realestateprogram')),
                ('sale_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='parcelaire.salefile')),
            ],
            options={
                'verbose_name': 'Alerte',
                'verbose_name_plural': 'Alertes',
                'ordering': ['-last_detected_at'],
                'indexes': [models.Index(fields=['status', 'level'], name='parcelaire__status_51ecc6_idx'), models.Index(fields=['rule', 'status'], name='parcelaire__rule_985c71_idx')],
            },
        ),
    ]
