# Generated by Django 4.2.29 on 2026-03-11 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0002_constructionproject_constructionupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionphoto',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='parcelaire.propertyasset'),
        ),
        migrations.AddField(
            model_name='constructionupdate',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='parcelaire.propertyasset'),
        ),
    ]
