# Generated by Django 4.2.29 on 2026-07-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0002_alert'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse e-mail')),
                ('label', models.CharField(blank=True, max_length=150, verbose_name='Nom / fonction')),
                ('with_financials', models.BooleanField(default=False, help_text='Sinon, les montants sont masqués dans le rapport reçu.', verbose_name='Reçoit les montants financiers')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Destinataire de rapport',
                'verbose_name_plural': 'Destinataires de rapports',
                'ordering': ['email'],
            },
        ),
    ]
