# Generated by Django 4.2.29 on 2026-04-20 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0002_remove_realestateprogram_has_orthophoto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramOrthophoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom')),
                ('slug', models.SlugField(blank=True, max_length=255, verbose_name='Slug')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='orthophotos/sources/', verbose_name='Fichier source')),
                ('tiles_folder', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dossier de tuiles')),
                ('tiles_url', models.CharField(blank=True, max_length=500, null=True, verbose_name='URL des tuiles')),
                ('min_zoom', models.PositiveSmallIntegerField(default=15, verbose_name='Zoom min')),
                ('max_zoom', models.PositiveSmallIntegerField(default=22, verbose_name='Zoom max')),
                ('max_native_zoom', models.PositiveSmallIntegerField(default=22, verbose_name='Zoom natif max')),
                ('bounds', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326, verbose_name='Emprise')),
                ('centroid', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Centroïde')),
                ('capture_date', models.DateField(blank=True, null=True, verbose_name='Date de prise de vue')),
                ('reference_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Année de référence')),
                ('reference_month', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mois de référence')),
                ('period_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='Libellé période')),
                ('version', models.CharField(blank=True, max_length=100, null=True, verbose_name='Version')),
                ('is_current', models.BooleanField(default=False, verbose_name='Orthophoto courante')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthophotos', to='parcelaire.realestateprogram', verbose_name='Programme')),
            ],
            options={
                'verbose_name': 'Orthophoto programme',
                'verbose_name_plural': 'Orthophotos programmes',
                'ordering': ['program__name', '-reference_year', '-reference_month', '-capture_date', '-created_at'],
                'indexes': [models.Index(fields=['program', 'is_current'], name='parcelaire__program_54210c_idx'), models.Index(fields=['program', 'reference_year', 'reference_month'], name='parcelaire__program_733e47_idx'), models.Index(fields=['program', 'capture_date'], name='parcelaire__program_023134_idx'), models.Index(fields=['is_active'], name='parcelaire__is_acti_dd5580_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='programorthophoto',
            constraint=models.UniqueConstraint(condition=models.Q(('reference_month__isnull', False), ('reference_year__isnull', False)), fields=('program', 'reference_year', 'reference_month'), name='uniq_program_orthophoto_month'),
        ),
        migrations.AddConstraint(
            model_name='programorthophoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('program',), name='uniq_current_orthophoto_per_program'),
        ),
    ]
