# Generated by Django 4.2.29 on 2026-03-13 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0003_constructionphoto_asset_constructionupdate_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='crm_last_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
