# Generated by Django 4.2.29 on 2026-08-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0003_reportrecipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programorthophoto',
            name='processed_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='orthophotos/processed/', verbose_name='GeoTIFF reprojeté (EPSG:3857)'),
        ),
        migrations.AlterField(
            model_name='programorthophoto',
            name='source_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='orthophotos/sources/', verbose_name='Fichier source'),
        ),
        migrations.AlterField(
            model_name='programorthophoto',
            name='vrt_file',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='orthophotos/processed/', verbose_name='VRT RGBA (si palette)'),
        ),
    ]
