# Generated by Django 4.2.29 on 2026-03-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0004_parcel_crm_last_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcel',
            name='valeur_hypothecaire',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
