# Generated by Django 4.2.29 on 2026-03-14 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0005_parcel_valeur_hypothecaire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parcel',
            options={'ordering': ['block__code', 'lot_number'], 'permissions': [('view_financial_data', 'Peut voir les données financières'), ('view_patient_data', 'Peut voir les données patient/client'), ('view_construction_data', 'Peut voir les données de construction'), ('view_parcellaire', 'Peut voir le parcellaire')]},
        ),
    ]
