# Generated by Django 4.2.29 on 2026-03-19 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcelaire', '0007_alter_parcel_centroid_alter_parcel_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='parcel',
            name='geometry',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
